compilers:
- compiler:
- compiler:
    spec: gcc@=13.2.0
    paths:
      cc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/gcc
      cxx: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/g++
      f77: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/gfortran
      fc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

