compilers:
- compiler:
    spec: gcc@=13.2.0
    paths:
      cc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/gcc
      cxx: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/g++
      f77: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/gfortran
      fc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-13.2.0/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=11.4.0
    paths:
      cc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-11.4.0/bin/gcc
      cxx: /share/apps/22.04/spack/environments/core/view/compilers/gcc-11.4.0/bin/g++
      f77: /share/apps/22.04/spack/environments/core/view/compilers/gcc-11.4.0/bin/gfortran
      fc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-11.4.0/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=7.5.0
    paths:
      cc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-7.5.0/bin/gcc
      cxx: /share/apps/22.04/spack/environments/core/view/compilers/gcc-7.5.0/bin/g++
      f77: /share/apps/22.04/spack/environments/core/view/compilers/gcc-7.5.0/bin/gfortran
      fc: /share/apps/22.04/spack/environments/core/view/compilers/gcc-7.5.0/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@=2023.2.0
    paths:
      cc: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/dpcpp
      f77: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: ['/share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/2023.2.1/linux/compiler/lib/intel64_lin']
- compiler:
    spec: oneapi@=2023.2.0
    paths:
      cc: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/icpx
      f77: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: ['/share/apps/22.04/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/2023.2.1/linux/compiler/lib/intel64_lin']
- compiler:
    spec: aocc@=4.1.0
    paths:
      cc: /share/apps/22.04/spack/environments/core/view/compilers/aocc-4.1.0/bin/clang
      cxx: /share/apps/22.04/spack/environments/core/view/compilers/aocc-4.1.0/bin/clang++
      f77: /share/apps/22.04/spack/environments/core/view/compilers/aocc-4.1.0/bin/flang
      fc: /share/apps/22.04/spack/environments/core/view/compilers/aocc-4.1.0/bin/flang
    flags:
      cflags: null
      cxxflags: null
      fflags: null
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
