mirrors:
  manual-mirror:
    fetch:
      url: file:///cvmfs/hpc.ucdavis.edu/sw/spack/manual-mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///cvmfs/hpc.ucdavis.edu/sw/spack/manual-mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
