modules:
  #prefix_inspections:
  #  lib64: [LD_LIBRARY_PATH]
  #  lib: [LD_LIBRARY_PATH]
  #  include:
  #  - CPATH
  #  - C_INCLUDE_PATH
  #  - CPLUS_INCLUDE_PATH
  default:
    enable::
      - tcl
    roots:
      tcl: $spack/../../modulefiles/spack/tcl
    arch_folder: false
    tcl:
      verbose: true
      hash_length: 0
      exclude_implicits: true
      projections:
        all: '{name}/{version}'
        target=zen2: '{name}/{version}+amd'
      all:
        template: hpccf/default.tcl
        prerequisites: direct
        conflict:
        - '{name}'
        environment:
          set:
            '{name}_ROOT': '{prefix}'

