config:
  install_tree:
    root: /cvmfs/hpc.ucdavis.edu/sw/spack/core
  template_dirs:
  - /cvmfs/hpc.ucdavis.edu/sw/spack/spack-ucdavis/templates
  db_lock_timeout: 60
  deprecated: true
  extensions:
  - /cvmfs/hpc.ucdavis.edu/sw/spack/spack-manager
