compilers:
- compiler:
    spec: clang@=14.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=9.5.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=13.2.0
    paths:
      cc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-13.2.0-y5biuspnetqjxpbwgrulzk2lyncskm6c/bin/gcc
      cxx: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-13.2.0-y5biuspnetqjxpbwgrulzk2lyncskm6c/bin/g++
      f77: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-13.2.0-y5biuspnetqjxpbwgrulzk2lyncskm6c/bin/gfortran
      fc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-13.2.0-y5biuspnetqjxpbwgrulzk2lyncskm6c/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=11.4.0
    paths:
      cc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-11.4.0-cxjhlgyxdo4ibtgmh2gwz3yfklafv7fb/bin/gcc
      cxx: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-11.4.0-cxjhlgyxdo4ibtgmh2gwz3yfklafv7fb/bin/g++
      f77: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-11.4.0-cxjhlgyxdo4ibtgmh2gwz3yfklafv7fb/bin/gfortran
      fc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/gcc-11.4.0-cxjhlgyxdo4ibtgmh2gwz3yfklafv7fb/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@=2023.2.0
    paths:
      cc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/dpcpp
      f77: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@=2023.2.0
    paths:
      cc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/icpx
      f77: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: ['/share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/intel-oneapi-compilers-2023.2.1-73sl4rcnnjvfa6p5b67n32w2xejl275l/compiler/2023.2.1/linux/compiler/lib/intel64_lin']
- compiler:
    spec: aocc@=4.1.0
    paths:
      cc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/aocc-4.1.0-4tyg3vta4lskiwned4ova5fa2ocmnikl/bin/clang
      cxx: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/aocc-4.1.0-4tyg3vta4lskiwned4ova5fa2ocmnikl/bin/clang++
      f77: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/aocc-4.1.0-4tyg3vta4lskiwned4ova5fa2ocmnikl/bin/flang
      fc: /share/apps/22.04/spack/opt/core/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/aocc-4.1.0-4tyg3vta4lskiwned4ova5fa2ocmnikl/bin/flang
    flags:
      cflags: null
      cxxflags: null
      fflags: null
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
