mirrors:
  manual-mirror:
    fetch:
      url: file:///share/apps/22.04/spack/manual-mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
    push:
      url: file:///share/apps/22.04/spack/manual-mirror
      access_pair:
      - null
      - null
      access_token: null
      profile: null
      endpoint_url: null
