compilers:
- compiler:
    spec: gcc@=9.5.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
      #- compiler:
      #    spec: gcc@=13.2.0
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-13.2.0/bin/gcc
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-13.2.0/bin/g++
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-13.2.0/bin/gfortran
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-13.2.0/bin/gfortran
      #    flags: {}
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
      #- compiler:
      #    spec: gcc@=11.4.0
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-11.4.0/bin/gcc
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-11.4.0/bin/g++
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-11.4.0/bin/gfortran
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-11.4.0/bin/gfortran
      #    flags: {}
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
      #- compiler:
      #    spec: gcc@=7.5.0
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-7.5.0/bin/gcc
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-7.5.0/bin/g++
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-7.5.0/bin/gfortran
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/gcc-7.5.0/bin/gfortran
      #    flags: {}
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
      #- compiler:
      #    spec: oneapi@=2023.2.0
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/icx
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/icpx
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/ifx
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/latest/linux/bin/ifx
      #    flags: {}
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: [/cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2023.2.1/compiler/2023.2.1/linux/compiler/lib/intel64_lin]
      #- compiler:
      #    spec: aocc@=4.1.0
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-4.1.0/bin/clang
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-4.1.0/bin/clang++
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-4.1.0/bin/flang
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-4.1.0/bin/flang
      #    flags:
      #      cflags: null
      #      cxxflags: null
      #      fflags: null
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
      #- compiler:
      #    spec: nvhpc@=22.9
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/nvhpc-22.9/Linux_x86_64/2022/compilers/bin/nvc
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/nvhpc-22.9/Linux_x86_64/2022/compilers/bin/nvc++
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/nvhpc-22.9/Linux_x86_64/2022/compilers/bin/nvfortran
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/nvhpc-22.9/Linux_x86_64/2022/compilers/bin/nvfortran
      #    flags: {}
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
      #- compiler:
      #    spec: intel@=2021.11.1
      #    paths:
      #      cc: null
      #      cxx: null
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2024.0.2/compiler/latest/bin/ifort
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2024.0.2/compiler/latest/bin/ifort
      #    flags: {}
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
      #- compiler:
      #    spec: oneapi@=2024.0.2
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2024.0.2/compiler/latest/bin/icx
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2024.0.2/compiler/latest/bin/icpx
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2024.0.2/compiler/latest/bin/ifx
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/intel-oneapi-compilers-2024.0.2/compiler/latest/bin/ifx
      #    flags: {}
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
      #- compiler:
      #    spec: aocc@=3.2.0
      #    paths:
      #      cc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-3.2.0/bin/clang
      #      cxx: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-3.2.0/bin/clang++
      #      f77: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-3.2.0/bin/flang
      #      fc: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/compilers/aocc-3.2.0/bin/flang
      #    flags:
      #      cflags: null
      #      cxxflags: null
      #      fflags: null
      #    operating_system: ubuntu22.04
      #    target: x86_64
      #    modules: []
      #    environment: {}
      #    extra_rpaths: []
