packages:

  hwloc:
    buildable: false
    externals:
    - spec: hwloc@2.9.1 target=x86_64_v3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/hwloc-2.9.1
    - spec: hwloc@2.9.1 target=zen2
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen2/hwloc-2.9.1
    - spec: hwloc@2.9.1 target=zen3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen3/hwloc-2.9.1

  libevent:
    buildable: false
    externals:
    - spec: libevent@2.1.12 target=x86_64_v3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/libevent-2.1.12
    - spec: libevent@2.1.12 target=zen2
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen2/libevent-2.1.12
    - spec: libevent@2.1.12 target=zen3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen3/libevent-2.1.12

  openmpi:
    buildable: false
    externals:
    - spec: openmpi@4.1.6 fabrics=ucx schedulers=slurm +legacylaunchers +cuda cuda_arch=75 target=x86_64_v3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/openmpi-4.1.6
    - spec: openmpi@4.1.6 fabrics=ucx schedulers=slurm +legacylaunchers +cuda cuda_arch=75 target=zen2
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen2/openmpi-4.1.6
    - spec: openmpi@4.1.6 fabrics=ucx schedulers=slurm +legacylaunchers +cuda cuda_arch=75 target=zen3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen3/openmpi-4.1.6

  pmix:
    buildable: false
    externals:
    - spec: pmix@4.2.6 target=x86_64_v3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/pmix-4.2.6
    - spec: pmix@4.2.6 target=zen2
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen2/pmix-4.2.6
    - spec: pmix@4.2.6 target=zen3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen3/pmix-4.2.6

  ucx:
    buildable: false
    externals:
    - spec: ucx@1.15.0 +thread_multiple target=x86_64_v3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/ucx-1.15.0
    - spec: ucx@1.15.0 +thread_multiple target=zen2
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen2/ucx-1.15.0
    - spec: ucx@1.15.0 +thread_multiple target=zen3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen3/ucx-1.15.0

  slurm:
    buildable: false
    externals:
    - spec: slurm@23-11-1-1 target=x86_64_v3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/slurm-23-11-1-1
    - spec: slurm@23-11-1-1 target=zen2
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen2/slurm-23-11-1-1
    - spec: slurm@23-11-1-1 target=zen3
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/zen3/slurm-23-11-1-1

  cuda:
    buildable: false
    externals:
    - spec: cuda@12.3.0
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/cuda-12.3.0
    - spec: cuda@11.7.1
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/cuda-11.7.1
    - spec: cuda@11.2.2
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/cuda-11.2.2
    - spec: cuda@8.0.61
      prefix: /cvmfs/hpc.ucdavis.edu/sw/spack/environments/core/view/generic/cuda-8.0.61

