repos:
  ucdavis:
    git: https://github.com/ucdavis/spack-ucdavis.git
    destination: /cvmfs/hpc.ucdavis.edu/sw/spack/repos/ucdavis-root
  builtin:
    git: https://github.com/spack/spack-packages.git
    branch: releases/v2025.07
    destination: /cvmfs/hpc.ucdavis.edu/sw/spack/repos/builtin-root
