compilers:
- compiler:
    spec: gcc@11.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.5.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/gcc
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/g++
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/gfortran
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@5.5.0
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/gcc
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/g++
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/gfortran
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-5kxkqox32gnd2diujboaq6blj7g4eapk/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@4.9.4
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-5.5.0/gcc-4.9.4-5ydwbb5y5o5dchudgux56iupo4takw4v/bin/gcc
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-5.5.0/gcc-4.9.4-5ydwbb5y5o5dchudgux56iupo4takw4v/bin/g++
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-5.5.0/gcc-4.9.4-5ydwbb5y5o5dchudgux56iupo4takw4v/bin/gfortran
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-5.5.0/gcc-4.9.4-5ydwbb5y5o5dchudgux56iupo4takw4v/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
