packages:

  # 
  # Our self-built slurm/openmpi stack
  #

  slurm:
    version:
      - 22-05-6-1
    variants: +pmix +mariadb +hwloc +restd sysconfdir=/etc/slurm
    require: "/xqrmrt7"

  hwloc:
    version:
      - 2.8.0
    variants: +netloc +pci +libxml2 +libudev +cairo +nvml

  cairo:
    require: "+X +ft +fc +pdf +png +gobject"

  python:
    require: "~libxml2"

  libxml2:
    require: "@2.10.2: +python"

  libevent:
    version:
      - 2.1.12

  pmix:
    version:
      - 4.1.2
      - 3.2.3

  ucx:
    version:
      - 1.13.1
    variants: +thread_multiple

  mpi:
    require:
    - one_of:
      - openmpi@4.1.4

  openmpi:
    version: 
      - 4.1.4
    require: "/wb2zk5p" # we want only one openmpi! convert to a `one_of` when we switch to arch-specific builds.
    variants: fabrics=ucx thread_multiple=True schedulers=slurm

  lmod:
    variants: modulepath_root=/share/apps/spack/modulefiles/

  munge:
    externals:
      - spec: munge@0.5.14 %gcc@11.3.0
        prefix: /usr
    buildable: false

  mariadb:
    externals:
      - spec: mariadb@10.8.2 %gcc@11.3.0
        prefix: /usr
    buildable: false

  at-spi2-core:
    externals:
      - spec: at-spi2-core@2.44.0 %gcc@11.3.0
        prefix: /usr
    buildable: false

  at-spi2-atk:
    externals:
      - spec: at-spi2-atk@2.38.0 %gcc@11.3.05
        prefix: /usr
    buildable: false

  intel-mkl:
    require: "@2017.0.098:" # force post-2017 MKLs that are OSS

  dbus:
    require: "@1.12.8 local_state_dir=/var/"

  #
  # Franklin has A4000, A5000, and eventually, RTX2080 GPUs
  # A4000 and A5000 are compute capability 8.6;
  # RTX2080 are 7.5.
  # For now, target the lowest common version.
  #
  cuda:
    variants: cuda_arch=75

  #
  # Spack-built package settings
  #

  all:
    target: [x86_64]
    compiler:
    - gcc@11.3.0

  #gdal:
  #  variants: +netcdf +sqlite3 +xml2 +grib +hdf5 +curl +geos +cfitsio +crypto +expat +gif +jasper +pcre +png +zstd

  gdl:
    version: [0.9.8]
    variants: +graphicsmagick +python

  sqlite:
    variants: +rtree

  r-genomicfeatures:
    version: [1.49.6]

  r-genomeinfodb:
    version: [1.35.1]

  r-bsgenome:
    version: [1.66.1]
