packages:
  openssh:
    buildable: false
    externals:
    - spec: openssh@8.9p1
      prefix: /usr
  #autoconf:
  #  externals:
  #  - spec: autoconf@2.71
  #    prefix: /usr
  mpi:
    require: openmpi
  tbb:
    require: intel-oneapi-tbb
  mkl:
    require: intel-oneapi-mkl
  munge:
    externals:
    - spec: munge@0.5.14 %gcc@11.3.0
      prefix: /usr
    buildable: false
  mariadb:
    externals:
    - spec: mariadb@10.8.2 %gcc@11.3.0
      prefix: /usr
    buildable: false
  at-spi2-core:
    externals:
    - spec: at-spi2-core@2.44.0 %gcc@11.3.0
      prefix: /usr
    buildable: false
  at-spi2-atk:
    externals:
    - spec: at-spi2-atk@2.38.0 %gcc@11.3.0
      prefix: /usr
    buildable: false
  atk:
    externals:
    - spec: atk@2.36.0
      prefix: /usr
    buildable: false
  intel-mkl:
    require: '@2017.0.098:'
  dbus:
    require: '@1.12.8 local_state_dir=/var/'
  gtkplus:
    buildable: false
    externals:
    - spec: gtkplus@3.24.33
      prefix: /usr
    - spec: gtkplus@2.24.33
      prefix: /usr
  wxwidgets:
    buildable: false
    externals:
    - spec: wxwidgets@3.0.2
      prefix: /usr
  opengl:
    buildable: false
    externals:
    - spec: opengl@4.5.0 %gcc@11.3.0
      prefix: /usr
  linux-pam:
    buildable: false
    externals:
    - spec: linux-pam@1.4.0 %gcc@11.3.0
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@3.0.2
      prefix: /usr
    #buildable: False

  rust:
    externals:
    - spec: rust@1.61.0
      prefix: /usr
  cvs:
    externals:
    - spec: cvs@1.12.13
      prefix: /usr
  subversion:
    externals:
    - spec: subversion@1.14.1
      prefix: /usr
  llvm:
    externals:
    - spec: llvm@14.0.0+clang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang-14
          cxx: /usr/bin/clang++-14
  ####

  slurm:
    require: '@22-05-6-1 +pmix +mariadb +hwloc +restd sysconfdir=/etc/slurm'
    version:
    - 22-05-6-1
    variants: +pmix +mariadb +hwloc +restd sysconfdir=/etc/slurm
  hwloc:
    # When mpi=openmpi, this introduces an unresolvable dependency.
    # See https://github.com/spack/spack/issues/15836 for details
    require: '@2.8.0 ~netloc +pci +libxml2 +libudev +nvml +cairo cuda_arch=75'
    version:
    - 2.8.0
    variants: +netloc +pci +libxml2 +libudev +cairo +nvml
  cairo:
    require: +X +ft +fc +pdf +png +gobject
  python:
    require: ~libxml2
  libxml2:
    require: '@2.10.2: +python'
  libevent:
    require: '@2.1.12'
    version:
    - 2.1.12
  pmix:
    require: '@4.1.2'
    version:
    - 4.1.2
  ucx:
    require: '@1.13.1 +thread_multiple'
    version:
    - 1.13.1
    variants: +thread_multiple
  openmpi:
    require:
    - any_of:
      - '@4.1.4 fabrics=ucx schedulers=slurm +legacylaunchers +cuda cuda_arch=75 target=x86_64_v3'
      - '@4.1.4 fabrics=ucx schedulers=slurm +legacylaunchers +cuda cuda_arch=75 target=zen2'
    version:
    - 4.1.4
    variants: fabrics=ucx schedulers=slurm +cuda +legacylaunchers
  lmod:
    require: '@8.7.14 modulepath_root=/share/apps/spack/modulefiles/'
    version:
    - 8.7.14
    variants: modulepath_root=/share/apps/spack/modulefiles/
  amdfftw:
    require: '@3.2 +openmp'
    version:
    - 3.2
    variants: +openmp
  intel-oneapi-mkl:
    require: '@2022.2.1'
    version:
    - 2022.2.1
  fftw:
    require: '@3.3.10 +openmp'
    version:
    - 3.3.10
    variants: +openmp

  cuda:
    version:
    - 11.7

  # see: https://github.com/spack/spack/issues/33178
  m4:
    require: '%gcc'

  all:
    target: [x86_64_v3, zen2]
    compiler:
    - gcc@11.3.0
    providers:
      tbb:
      - intel-oneapi-tbb
    variants:
    - cuda_arch=75

  gdal:
    variants: +netcdf +sqlite3 +xml2 +grib +hdf5 +curl +geos +cfitsio +crypto +expat
      +gif +jasper +pcre +png +zstd
  gdl:
    version: [0.9.8]
    variants: +graphicsmagick +python
  sqlite:
    variants: +rtree
  r-genomicfeatures:
    version: [1.49.6]
  r-genomeinfodb:
    version: [1.35.1]
  r-bsgenome:
    version: [1.66.1]
