compilers:
- compiler:
    spec: gcc@11.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.5.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-xllshg4qogxno5yfusupkvw6fvsgo4xz/bin/gcc
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-xllshg4qogxno5yfusupkvw6fvsgo4xz/bin/g++
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-xllshg4qogxno5yfusupkvw6fvsgo4xz/bin/gfortran
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/gcc-7.5.0-xllshg4qogxno5yfusupkvw6fvsgo4xz/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@5.5.0
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-5.5.0-qd3ezwpsl3jooc5tzxzti4xigoor7b2l/bin/gcc
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-5.5.0-qd3ezwpsl3jooc5tzxzti4xigoor7b2l/bin/g++
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-5.5.0-qd3ezwpsl3jooc5tzxzti4xigoor7b2l/bin/gfortran
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-5.5.0-qd3ezwpsl3jooc5tzxzti4xigoor7b2l/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@4.9.4
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-4.9.4-2ezpkyy2h6jqjqiwlbwpymgas5mex2lm/bin/gcc
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-4.9.4-2ezpkyy2h6jqjqiwlbwpymgas5mex2lm/bin/g++
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-4.9.4-2ezpkyy2h6jqjqiwlbwpymgas5mex2lm/bin/gfortran
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-9.5.0/gcc-4.9.4-2ezpkyy2h6jqjqiwlbwpymgas5mex2lm/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /usr/bin/clang-14
      cxx: /usr/bin/clang++-14
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
