packages:

  mpi:
    require: openmpi

  tbb:
    require: intel-oneapi-tbb

  mkl:
    require: intel-oneapi-mkl

  munge:
    externals:
      - spec: munge@0.5.13
        prefix: /usr
    buildable: false

  mariadb:
    externals:
      - spec: mariadb@10.3.37
        prefix: /usr
    buildable: false

  at-spi2-core:
    externals:
      - spec: at-spi2-core@2.36.0
        prefix: /usr
    buildable: false

  at-spi2-atk:
    externals:
      - spec: at-spi2-atk@2.35.1
        prefix: /usr
    buildable: false

  intel-mkl:
    require: "@2017.0.098:" # force post-2017 MKLs that are OSS

  dbus:
    require: "@1.12.8 local_state_dir=/var/"

  openssl:
    externals:
    - spec: openssl@1.1.1f
      prefix: /usr
    buildable: False

  slurm:
    require: "@22-05-6-1 +pmix +mariadb +hwloc +restd sysconfdir=/etc/slurm"
    version:
    - 22-05-6-1
    variants: +pmix +mariadb +hwloc +restd sysconfdir=/etc/slurm
  
  hwloc:
    # When mpi=openmpi, this introduces an unresolvable dependency.
    # See https://github.com/spack/spack/issues/15836 for details
    require: "@2.8.0 ~netloc +pci +libxml2 +libudev +cairo cuda_arch=75"
    version:
    - 2.8.0
    variants: +netloc +pci +libxml2 +libudev +cairo

  cairo:
    require: +X +ft +fc +pdf +png +gobject

  python:
    require: ~libxml2

  libxml2:
    require: '@2.10.2: +python'

  libevent:
    require: "@2.1.12"
    version:
    - 2.1.12
 
  pmix:
    require: "@4.1.2"
    version:
    - 4.1.2
 
  ucx:
    require: "@1.13.1 +thread_multiple"
    version:
    - 1.13.1
    variants: +thread_multiple
 
  openmpi:
    require:
      - any_of:
        - "@4.1.4 fabrics=ucx schedulers=slurm"
    version:
    - 4.1.4
    variants: fabrics=ucx schedulers=slurm

  lmod:
    require: "@8.7.14 modulepath_root=/share/apps/spack/modulefiles/"
    version:
    - 8.7.14
    variants: modulepath_root=/share/apps/spack/modulefiles/

  #
  # Spack-built package settings
  #

  all:
    target: [x86_64]
    compiler:
    - gcc@9.4.0
    providers:
      tbb:
        - intel-oneapi-tbb

  sqlite:
    variants: +rtree

