compilers:
- compiler:
    spec: gcc@5.5.0
    paths:
      cc: /usr/bin/gcc-5
      cxx: /usr/bin/g++-5
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/gcc
      cxx: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/g++
      f77: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/gfortran
      fc: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/gfortran
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.7.1
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/intel64/icc
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/intel64/icpc
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/intel64/ifort
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/intel64/ifort
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@2022.2.1
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/icx
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/dpcpp
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/ifx
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2022.2.1
    paths:
      cc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/icx
      cxx: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/icpx
      f77: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/ifx
      fc: /share/apps/spack/spack-v0.19/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-emmtgavvau4zt54suxbzqw25znqx2cko/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
