modules:
  default:
    enable:
      - tcl
    roots:
      tcl: $spack/../modulefiles/spack
    arch_folder: false
    tcl:
      verbose: true
      #autoload: 'direct'
      all:
        template: hpccf/default.tcl
        prerequisites: direct
        conflict:
        - '{name}'
        environment:
          set:
            '{name}_ROOT': '{prefix}'
      circos:
        template: hpccf/circos-version-warning.tcl
