compilers:
- compiler:
    spec: gcc@11.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.5.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /usr/bin/clang-14
      cxx: /usr/bin/clang++-14
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=7.5.0
    paths:
      cc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/gcc-7.5.0-wk3qbbmxsx4g5eew6uzvi4vlamj5zq3k/bin/gcc
      cxx: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/gcc-7.5.0-wk3qbbmxsx4g5eew6uzvi4vlamj5zq3k/bin/g++
      f77: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/gcc-7.5.0-wk3qbbmxsx4g5eew6uzvi4vlamj5zq3k/bin/gfortran
      fc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/gcc-7.5.0-wk3qbbmxsx4g5eew6uzvi4vlamj5zq3k/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=5.5.0
    paths:
      cc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-5.5.0-eypibrd56kuk3zpvezvvnn3qjpc5knwu/bin/gcc
      cxx: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-5.5.0-eypibrd56kuk3zpvezvvnn3qjpc5knwu/bin/g++
      f77: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-5.5.0-eypibrd56kuk3zpvezvvnn3qjpc5knwu/bin/gfortran
      fc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-5.5.0-eypibrd56kuk3zpvezvvnn3qjpc5knwu/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=4.9.4
    paths:
      cc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-4.9.4-f7ftarvmg3uikemzefghlmu3q6sqkmv6/bin/gcc
      cxx: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-4.9.4-f7ftarvmg3uikemzefghlmu3q6sqkmv6/bin/g++
      f77: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-4.9.4-f7ftarvmg3uikemzefghlmu3q6sqkmv6/bin/gfortran
      fc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-9.5.0/gcc-4.9.4-f7ftarvmg3uikemzefghlmu3q6sqkmv6/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@=2022.2.1
    paths:
      cc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/dpcpp
      f77: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@=2022.2.1
    paths:
      cc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/icpx
      f77: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/spack-root/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-ludgpxxgyrhramquhp7xxotgjm7xpq6n/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

