compilers:
- compiler:
    spec: gcc@5.5.0
    paths:
      cc: /usr/bin/gcc-5
      cxx: /usr/bin/g++-5
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@11.2.0
    paths:
      cc: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/gcc
      cxx: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/g++
      f77: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/gfortran
      fc: /share/apps/spack-v0.17.1/opt/spack/linux-ubuntu18.04-x86_64/gcc-11.2.0/gcc-11.2.0-6ll4vbi6dn34fyt4fwtrj4whi2hejmhf/bin/gfortran
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
