modules:
  tcl:
    verbose: True
    all:
      template: 'hpccf/default.tcl'
      conflict:
        - '{name}'
      environment:
        set:
          '{name}_ROOT': '{prefix}'
      #autoload: 'direct'
    circos:
      template: 'hpccf/circos-version-warning.tcl'
