compilers:
- compiler:
    spec: gcc@11.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.5.0
    paths:
      cc: /usr/bin/gcc-9
      cxx: /usr/bin/g++-9
      f77: /usr/bin/gfortran-9
      fc: /usr/bin/gfortran-9
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /usr/bin/clang-14
      cxx: /usr/bin/clang++-14
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: intel@2021.7.1
    paths:
      cc: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/intel64/icc
      cxx: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/intel64/icpc
      f77: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/intel64/ifort
      fc: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/intel64/ifort
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: dpcpp@2022.2.1
    paths:
      cc: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/dpcpp
      f77: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: oneapi@2022.2.1
    paths:
      cc: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/icx
      cxx: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/icpx
      f77: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/ifx
      fc: /share/apps/22.04/spack/spack-v0.19.1/opt/spack/linux-ubuntu22.04-x86_64_v2/gcc-11.3.0/intel-oneapi-compilers-2022.2.1-yekltmvwxmmpqwoe7u42brvfxcb5nmm4/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
