modules:
  default:
    enable::
      - tcl
    roots:
      lmod: $spack/../../modulefiles/spack/
      tcl: $spack/../../modulefiles/spack/
    arch_folder: false
    lmod:
      core_compilers:
        - 'gcc@11.3.0'
        - 'gcc@9.5.0'
      hierarchy:: []
      hash_length: 0
      exclude_implicits: true
      include:
        - gcc
      projections:
        all: '{name}/{version}'
        target=zen2: '{name}/{version}+amd'
      defaults:
        - target=x86_64
      all:
        template: hpccf/default.lua
        autoload: direct
        environment:
          set:
            '{name}_ROOT': '{prefix}'

    tcl:
      verbose: true
      hash_length: 0
      exclude_implicits: true
      projections:
        all: '{name}/{version}'
        target=zen2: '{name}/{version}+amd'
      all:
        template: hpccf/default.tcl
        prerequisites: direct
        conflict:
        - '{name}'
        environment:
          set:
            '{name}_ROOT': '{prefix}'
      circos:
        template: hpccf/circos-version-warning.tcl
